name: Deploy on Azure App Services

on: [push]

concurrency: Production

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_PACKAGE_PATH: dist/app.zip
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: |
          npm install
          npm run build
          npm run package

      - uses: actions/upload-artifact@v4
        with:
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-development:
    needs: build
    runs-on: ubuntu-latest
    environment: development
    if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_APP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    if: github.ref == 'refs/heads/release'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_APP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/production'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_APP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
